### ISSUE TITLE
Generated models contain duplicate ApplicationInstance identifiers

### ISSUE THREAD

**Issue by fjouault** [IncQueryLabs/incquery-examples-cps#73]
The Cyber Physical System domain specification at:
https://github.com/IncQueryLabs/incquery-examples-cps/wiki/Domains
states that ApplicationInstances must have unique identifiers.

However, it seems that:
* models initially passed to transformations during performance tests sometimes have duplicate identifiers
* changes performed after the initial run of transformations have duplicate identifiers (generated ApplicationInstances seem to all have the same identifier)

The following code can be used to detect such issues:
```
val appInstanceIdentifiers = cps2dep.cps.eAllContents.filter(ApplicationInstance).map[it.identifier].toList
val uniqueAppInstanceIdentifiers = new LinkedHashSet
appInstanceIdentifiers.forEach[
	assertTrue('''At least one non-unique ApplicationInstance identifier: «it»''', uniqueAppInstanceIdentifiers.add(it))
]
```

**Comment by abelhegedus** [comment]
Initial generation in case of statistics based case is fixed in: https://git.eclipse.org/c/viatra/org.eclipse.viatra.examples.git/commit/?id=747f5630607ccce414aced891299354c57e48a68
Unique id generation in modification phase is added in: https://github.com/IncQueryLabs/viatra-cps-benchmark/commit/9414e2bf8b5def0c2b31ce4a89060ded2e390122
